// ระบบ 2 ภาษา (i18n) แบบ central table — ใช้ได้ทั้งใน widget และ enum
// ค่าเริ่มต้น = English, เลือกไทยได้ในตั้งค่า
//
// วิธีใช้: tr('key')  → คืนข้อความตามภาษาปัจจุบัน (appLang)
// appLang ถูก sync โดย settingsProvider เมื่อผู้ใช้เปลี่ยนภาษา

/// ภาษาปัจจุบันของแอป ('en' | 'th') — sync จาก settings
String appLang = 'en';

/// ภาษาที่รองรับ
const List<String> kSupportedLangs = ['en', 'th'];

/// แปลข้อความตาม key (fallback: en → key เอง)
String tr(String key) {
  final entry = _strings[key];
  if (entry == null) return key;
  return entry[appLang] ?? entry['en'] ?? key;
}

/// แทรกค่าในข้อความ เช่น trp('greeting.age', {'age': '70'})
String trp(String key, Map<String, String> params) {
  var s = tr(key);
  params.forEach((k, v) => s = s.replaceAll('{$k}', v));
  return s;
}

const Map<String, Map<String, String>> _strings = {
  // ── App / common ──
  'app.tagline': {'en': 'A Brain Tracker App', 'th': 'แอปฝึกสมองและดูแลสุขภาพ'},
  'common.cancel': {'en': 'Cancel', 'th': 'ยกเลิก'},
  'common.delete': {'en': 'Delete', 'th': 'ลบ'},
  'common.save': {'en': 'Save', 'th': 'บันทึก'},
  'common.close': {'en': 'Close', 'th': 'ปิด'},
  'common.ok': {'en': 'OK', 'th': 'ตกลง'},
  'common.edit': {'en': 'Edit', 'th': 'แก้ไข'},
  'common.add': {'en': 'Add', 'th': 'เพิ่ม'},
  'common.test': {'en': 'Test now', 'th': 'ทดสอบตอนนี้'},

  // ── Language ──
  'lang.title': {'en': 'Language', 'th': 'ภาษา'},
  'lang.en': {'en': 'English', 'th': 'English'},
  'lang.th': {'en': 'ไทย (Thai)', 'th': 'ไทย'},

  // ── Bottom navigation ──
  'nav.games': {'en': 'Brain', 'th': 'ฝึกสมอง'},
  'nav.assessment': {'en': 'Assess', 'th': 'ประเมิน'},
  'nav.screenTime': {'en': 'Screen', 'th': 'จำกัดเวลา'},
  'nav.settings': {'en': 'Settings', 'th': 'ตั้งค่า'},

  // ── Home ──
  'home.appbar': {'en': 'Brain Training', 'th': 'ฝึกสมอง'},
  'home.hello': {'en': 'Hello!', 'th': 'สวัสดี!'},
  'home.howAreYou': {'en': 'How are you today?', 'th': 'วันนี้เป็นอย่างไรบ้าง?'},
  'home.historyTooltip': {'en': 'Score history', 'th': 'ประวัติคะแนน'},
  'home.familyCall.title': {'en': 'Call Family', 'th': 'โทรหาครอบครัว'},
  'home.familyCall.subtitle':
      {'en': 'Tap to call children instantly', 'th': 'กดโทรหาลูกหลานได้ทันที'},
  'home.appointment.title': {'en': 'Doctor Appointments', 'th': 'นัดหมายแพทย์'},
  'home.appointment.subtitle':
      {'en': 'Save visits, get reminded early', 'th': 'บันทึกนัด แล้วเตือนก่อนถึงเวลา'},
  'home.scam.title': {'en': 'Scam Message Check', 'th': 'ตรวจข้อความหลอกลวง'},
  'home.scam.subtitle':
      {'en': 'Paste an SMS to check if it is safe', 'th': 'วางข้อความ SMS มาเช็กว่าปลอดภัยไหม'},
  'home.soundMatch.title': {'en': 'Sound Match', 'th': 'จับคู่เสียง'},
  'home.soundMatch.subtitle':
      {'en': 'Train listening memory', 'th': 'ฝึกความจำด้านการฟัง'},
  'home.memoryMatch.title': {'en': 'Picture Match', 'th': 'จับคู่ภาพ'},
  'home.memoryMatch.subtitle':
      {'en': 'Train visual memory', 'th': 'ฝึกความจำด้านภาพ'},
  'home.colorSequence.title': {'en': 'Tap in Order', 'th': 'กดปุ่มตามลำดับ'},
  'home.colorSequence.subtitle':
      {'en': 'Train memory and focus', 'th': 'ฝึกความจำและการสังเกต'},

  // ── Assessment tab (home) ──
  'assessment.tab.title': {'en': 'Brain Health Check', 'th': 'ประเมินสุขภาพสมอง'},
  'assessment.tab.ready': {'en': 'Ready to start?', 'th': 'พร้อมประเมินหรือยัง?'},
  'assessment.tab.desc': {
    'en': 'Take the assessment to see your brain health',
    'th': 'ทำแบบประเมินเพื่อดูสุขภาพสมองของคุณ'
  },
  'assessment.tab.start': {'en': 'Start Assessment', 'th': 'เริ่มประเมิน'},
  'assess.step.dateTime': {'en': 'Day/Time', 'th': 'วัน/เวลา'},
  'assess.step.memorize': {'en': 'Memorize', 'th': 'จำคำ 3 คำ'},
  'assess.step.countdown': {'en': 'Countdown', 'th': 'นับถอยหลัง'},
  'assess.step.recall': {'en': 'Recall', 'th': 'จำคำได้ไหม'},

  // ── Onboarding ──
  'onboarding.welcome': {'en': 'Welcome to Demenish AI', 'th': 'ยินดีต้อนรับสู่ Demenish AI'},
  'onboarding.subtitle': {
    'en': 'Tell us a bit to personalize the app\n(optional — you can set it later in Settings)',
    'th': 'บอกเราหน่อยเพื่อปรับแอปให้เหมาะกับคุณ\n(ข้ามได้ แล้วมาตั้งทีหลังที่หน้าตั้งค่า)'
  },
  'onboarding.name': {'en': 'Your name', 'th': 'ชื่อของคุณ'},
  'onboarding.nameHint': {'en': 'e.g. John', 'th': 'เช่น สมชาย'},
  'onboarding.age': {'en': 'Age range', 'th': 'ช่วงอายุ'},
  'onboarding.gender': {'en': 'Gender', 'th': 'เพศ'},
  'onboarding.start': {'en': 'Get Started', 'th': 'เริ่มใช้งาน'},
  'onboarding.skip': {'en': 'Skip for now', 'th': 'ข้ามไปก่อน'},

  // ── Profile ──
  'profile.title': {'en': 'My Info', 'th': 'ข้อมูลของฉัน'},
  'profile.name': {'en': 'Name', 'th': 'ชื่อ'},
  'profile.nameHint': {'en': 'Your name', 'th': 'ชื่อของคุณ'},
  'profile.family': {'en': 'Family Members', 'th': 'รายชื่อครอบครัว'},
  'profile.familyCount': {'en': '{n} people', 'th': '{n} คน'},

  // ── Settings ──
  'settings.title': {'en': 'Settings', 'th': 'ตั้งค่า'},
  'settings.myInfo': {'en': 'My Info', 'th': 'ข้อมูลของฉัน'},
  'settings.myInfoHint':
      {'en': 'Tap to set name, age and gender', 'th': 'แตะเพื่อตั้งชื่อ อายุ และเพศ'},
  'settings.theme': {'en': 'Theme Mode', 'th': 'โหมดธีม'},
  'settings.background': {'en': 'Background Color', 'th': 'สีพื้นหลัง'},
  'home.dateLabel': {'en': 'Date', 'th': 'วันที่'},
  'bg.default': {'en': 'Default', 'th': 'ค่าเริ่มต้น'},
  'bg.cream': {'en': 'Cream', 'th': 'ครีม'},
  'bg.lightBlue': {'en': 'Light Blue', 'th': 'ฟ้าอ่อน'},
  'bg.lightGreen': {'en': 'Light Green', 'th': 'เขียวอ่อน'},
  'bg.lightPink': {'en': 'Light Pink', 'th': 'ชมพูอ่อน'},
  'bg.lightPurple': {'en': 'Light Purple', 'th': 'ม่วงอ่อน'},
  'bg.lightOrange': {'en': 'Light Orange', 'th': 'ส้มอ่อน'},
  'bg.lightGray': {'en': 'Light Gray', 'th': 'เทาอ่อน'},
  'settings.font': {'en': 'Font', 'th': 'ฟอนต์'},
  'settings.fontSize': {'en': 'Text Size', 'th': 'ขนาดตัวอักษร'},
  'settings.familyLine': {'en': 'Notify Family via LINE', 'th': 'แจ้งครอบครัวผ่าน LINE'},
  // missing cancel/delete/edit keys used by appt/family screens
  'appt.cancel': {'en': 'Cancel', 'th': 'ยกเลิก'},
  'appt.delete': {'en': 'Delete', 'th': 'ลบ'},
  'family.cancel': {'en': 'Cancel', 'th': 'ยกเลิก'},
  'family.delete': {'en': 'Delete', 'th': 'ลบ'},
  'family.edit': {'en': 'Edit', 'th': 'แก้ไข'},
  // settings — data management + theme/font section headers + font preview
  'settings.appDescription': {
    'en': 'Brain training & wellbeing app for older adults',
    'th': 'แอปฝึกสมองและดูแลสุขภาพสำหรับผู้สูงอายุ'
  },
  'settings.version': {'en': 'Version {v}', 'th': 'เวอร์ชัน {v}'},
  'settings.manageData': {'en': 'Manage data', 'th': 'จัดการข้อมูล'},
  'settings.deleteAllTitle': {'en': 'Delete all data?', 'th': 'ลบข้อมูลทั้งหมด?'},
  'settings.deleteAllConfirm': {
    'en': 'Assessment scores, game scores and settings will all be deleted',
    'th': 'คะแนนประเมิน คะแนนเกม และการตั้งค่าจะถูกลบหมด'
  },
  'settings.deleteAllConfirmBtn': {'en': 'Delete all', 'th': 'ลบทั้งหมด'},
  'settings.deleteAllDone': {'en': 'All data deleted', 'th': 'ลบข้อมูลเรียบร้อยแล้ว'},
  'settings.deleteAllButton': {'en': 'Delete all data', 'th': 'ลบข้อมูลทั้งหมด'},
  'settings.sampleText': {'en': 'Sample text', 'th': 'ตัวอย่างข้อความ'},
  'settings.samplePreview':
      {'en': 'Hello, how are you today?', 'th': 'สวัสดี วันนี้เป็นอย่างไรบ้าง?'},
  'settings.fontSample': {'en': 'Aa Bb Cc', 'th': 'ก ข ค'},
  'settings.fontSampleLetter': {'en': 'A', 'th': 'อ'},
  // screen time — short time units (locale-aware formatter)
  'screen.unitH': {'en': 'h', 'th': 'ชม.'},
  'screen.unitMin': {'en': 'min', 'th': 'น.'},
  'screen.unitSec': {'en': 's', 'th': 'วิ.'},
  'screen.unitHourLong': {'en': 'h', 'th': 'ชั่วโมง'},
  'screen.unitMinLong': {'en': 'min', 'th': 'นาที'},
  // game enum labels
  'game.color.red': {'en': 'Red', 'th': 'แดง'},
  'game.color.green': {'en': 'Green', 'th': 'เขียว'},
  'game.color.blue': {'en': 'Blue', 'th': 'น้ำเงิน'},
  'game.color.yellow': {'en': 'Yellow', 'th': 'เหลือง'},
  'game.memoryMatch.easy': {'en': 'Easy', 'th': 'ง่าย'},
  'game.memoryMatch.medium': {'en': 'Medium', 'th': 'ปานกลาง'},
  'game.memoryMatch.hard': {'en': 'Hard', 'th': 'ยาก'},
  'game.memoryMatch.cardCount': {'en': '{n} cards', 'th': '{n} การ์ด'},
  'settings.familyLineHint': {
    'en': 'Family scans a QR to receive alerts',
    'th': 'ให้ลูกหลานสแกน QR แอดเพื่อรับแจ้งเตือน'
  },

  // ── Screen distance (settings section) ──
  'sd.title': {'en': 'Screen Distance Alert', 'th': 'เตือนระยะห่างหน้าจอ'},
  'sd.desc': {
    'en': 'Uses the front camera periodically (only while the app is open). '
        'Warns you to move back if you sit too close.',
    'th': 'ใช้กล้องหน้าตรวจเป็นช่วง เฉพาะตอนเปิดแอป '
        'ถ้านั่งใกล้จอเกินไปจะเตือนให้ถอยห่าง'
  },
  'sd.every': {'en': 'Check every', 'th': 'ตรวจทุก'},
  'sd.tooClose': {'en': 'Too close, please move back a bit', 'th': 'นั่งใกล้เกินไป ถอยห่างอีกนิดนะ'},
  'sd.good': {'en': 'Distance looks good', 'th': 'ระยะห่างกำลังดี'},
  'sd.noFace': {'en': 'No face found, look at the camera and retry', 'th': 'ไม่พบใบหน้า ลองมองที่กล้องแล้วลองใหม่'},
  'sd.warn': {'en': 'Sitting too close — move back to protect your eyes', 'th': 'นั่งใกล้จอเกินไป ถอยห่างอีกนิดนะ เพื่อถนอมสายตา'},

  // ── Drowsiness (settings section) ──
  'drowsy.title': {'en': 'Drowsiness Detection', 'th': 'ตรวจจับอาการง่วง'},
  'drowsy.desc': {
    'en': 'Uses the front camera periodically (only while the app is open). '
        'If drowsiness is detected, warns you to rest and alerts family via LINE.',
    'th': 'ใช้กล้องหน้าตรวจเป็นช่วง เฉพาะตอนเปิดแอป '
        'ถ้าพบว่ากำลังง่วง จะเตือนให้พัก และแจ้งครอบครัวผ่าน LINE'
  },
  'drowsy.lineReady': {'en': 'LINE: ready to notify', 'th': 'LINE: พร้อมส่งแจ้งเตือน'},
  'drowsy.lineNotReady': {'en': 'LINE: not configured (see docs/backend)', 'th': 'LINE: ยังไม่ได้ตั้งค่า (ดู docs/backend)'},
  'drowsy.warn': {'en': 'You seem drowsy — rest your eyes for a moment', 'th': 'ดูเหมือนกำลังง่วง พักสายตาสักครู่นะ'},
  'common.minutes': {'en': '{n} min', 'th': '{n} นาที'},

  // ── Notification channels (Android system settings) ──
  'notif.channel.apptName': {'en': 'Appointment reminders', 'th': 'การแจ้งเตือนนัดหมาย'},
  'notif.channel.apptDesc':
      {'en': 'Reminders before doctor appointments', 'th': 'เตือนก่อนถึงเวลานัดหมายแพทย์'},
  'notif.channel.alertName': {'en': 'Health alerts', 'th': 'การแจ้งเตือนสุขภาพ'},
  'notif.channel.alertDesc': {
    'en': 'Rest/eye-break reminders when fatigue is detected',
    'th': 'เตือนพักสายตา/พักผ่อนเมื่อพบสัญญาณเหนื่อยล้า'
  },

  // ── Enums: AgeRange ──
  'age.below60': {'en': 'Under 60', 'th': 'ต่ำกว่า 60 ปี'},
  'age.60to69': {'en': '60–69', 'th': '60–69 ปี'},
  'age.70to79': {'en': '70–79', 'th': '70–79 ปี'},
  'age.80plus': {'en': '80+', 'th': '80 ปีขึ้นไป'},

  // ── Enums: Gender ──
  'gender.male': {'en': 'Male', 'th': 'ชาย'},
  'gender.female': {'en': 'Female', 'th': 'หญิง'},
  'gender.unspecified': {'en': 'Not specified', 'th': 'ไม่ระบุ'},

  // ── Enums: FontScale ──
  'fontscale.small': {'en': 'Small', 'th': 'เล็ก'},
  'fontscale.normal': {'en': 'Normal', 'th': 'ปกติ'},
  'fontscale.large': {'en': 'Large', 'th': 'ใหญ่'},
  'fontscale.extraLarge': {'en': 'Extra Large', 'th': 'ใหญ่มาก'},

  // ── Enums: Font descriptions ──
  'font.sarabun.desc': {'en': 'Easy to read, clean', 'th': 'อ่านง่าย เรียบ'},
  'font.kanit.desc': {'en': 'Modern, rounded', 'th': 'ทันสมัย โค้งมน'},
  'font.prompt.desc': {'en': 'Clean, sharp', 'th': 'สะอาดตา คมชัด'},
  'font.mitr.desc': {'en': 'Friendly, cute', 'th': 'เป็นมิตร น่ารัก'},
  'font.noto.desc': {'en': 'Standard, complete', 'th': 'มาตรฐาน ครบทุกตัว'},

  // ── Enums: ThemeMode ──
  'theme.light': {'en': 'Light', 'th': 'สว่าง'},
  'theme.dark': {'en': 'Dark', 'th': 'มืด'},
  'theme.system': {'en': 'System', 'th': 'ตามระบบ'},
  "game.playAgain": {"en": "Play Again", "th": "เล่นอีกครั้ง"},
  "game.goHome": {"en": "Back to Home", "th": "กลับหน้าหลัก"},
  "game.itemNumber": {"en": "Q {n}", "th": "ข้อ {n}"},
  "game.exit.title": {"en": "Quit game?", "th": "ออกจากเกม?"},
  "game.exit.message": {"en": "Your score won't be saved", "th": "คะแนนจะไม่ถูกบันทึก"},
  "game.result.title": {"en": "Your Score", "th": "ผลคะแนน"},
  "game.result.outOf": {"en": "out of {total}", "th": "จาก {total}"},
  "game.result.goodMessage": {"en": "Excellent! 🎉", "th": "ยอดเยี่ยม! 🎉"},
  "game.result.okMessage": {"en": "Great job! 👍", "th": "ดีมาก! 👍"},
  "game.result.fairMessage": {"en": "Not bad, try again 💪", "th": "พอใช้ ลองอีกครั้ง 💪"},
  "game.result.lowMessage": {"en": "Try again 🙂", "th": "ลองใหม่นะ 🙂"},
  "game.result.goodSub": {"en": "Very well done", "th": "ทำได้ดีเยี่ยม"},
  "game.result.okSub": {"en": "Well done, keep practicing a little more", "th": "ทำได้ดี ลองฝึกเพิ่มอีกนิด"},
  "game.result.fairSub": {"en": "Keep practicing, you'll get better", "th": "ค่อย ๆ ฝึก จะดีขึ้นเรื่อย ๆ"},
  "game.result.lowSub": {"en": "It's okay, give it another try", "th": "ไม่เป็นไร ลองเล่นอีกครั้ง"},
  "game.soundMatch.title": {"en": "Sound Match", "th": "จับคู่เสียง"},
  "game.soundMatch.startHeading": {"en": "Sound Match Game", "th": "เกมจับคู่เสียง"},
  "game.soundMatch.startDesc": {"en": "Listen to the word, then pick the matching picture", "th": "ฟังเสียงคำศัพท์ แล้วเลือกรูปที่ตรงกัน"},
  "game.soundMatch.readySpeaker": {"en": "Turn on your speaker 🔊", "th": "เปิดลำโพงให้พร้อม 🔊"},
  "game.soundMatch.startButton": {"en": "Start Playing", "th": "เริ่มเล่น"},
  "game.soundMatch.tapImage": {"en": "Tap the picture that matches the sound", "th": "แตะรูปที่ตรงกับเสียง"},
  "game.soundMatch.hintWord": {"en": "💡 \"{word}\"", "th": "💡 \"{word}\""},
  "game.soundMatch.showWord": {"en": "Can't hear? Show the word", "th": "ไม่ได้ยิน? แสดงคำ"},
  "game.soundMatch.listenAgain": {"en": "Listen again", "th": "ฟังอีกครั้ง"},
  "game.soundMatch.goodSub": {"en": "Excellent listening memory", "th": "ความจำด้านการฟังดีเยี่ยม"},
  "game.memoryMatch.title": {"en": "Picture Match", "th": "จับคู่ภาพ"},
  "game.memoryMatch.titleWithLevel": {"en": "Picture Match ({level})", "th": "จับคู่ภาพ ({level})"},
  "game.memoryMatch.chooseDifficulty": {"en": "Choose difficulty", "th": "เลือกระดับความยาก"},
  "game.memoryMatch.resultTitle": {"en": "Picture Match Result", "th": "ผลเกมจับคู่ภาพ"},
  "game.memoryMatch.goodMessage": {"en": "Amazing memory! 🎉", "th": "ความจำเยี่ยม! 🎉"},
  "game.memoryMatch.okMessage": {"en": "Good memory! 👍", "th": "จำได้ดี! 👍"},
  "game.memoryMatch.fairMessage": {"en": "Not bad, try again 💪", "th": "พอใช้ ลองอีกครั้ง 💪"},
  "game.memoryMatch.lowMessage": {"en": "Keep practicing 🙂", "th": "ค่อย ๆ ฝึกนะ 🙂"},
  "game.memoryMatch.goodSub": {"en": "Matched all {pairs} pairs in {attempts} tries — great work!", "th": "จับคู่ครบ {pairs} คู่ ใน {attempts} ครั้ง — เก่งมาก!"},
  "game.memoryMatch.okSub": {"en": "{attempts} tries for {pairs} pairs — practice more and you'll improve", "th": "ใช้ {attempts} ครั้ง สำหรับ {pairs} คู่ ลองฝึกเพิ่มจะดีขึ้น"},
  "game.memoryMatch.fairSub": {"en": "{attempts} tries — keep practicing remembering positions", "th": "ใช้ {attempts} ครั้ง ค่อย ๆ ฝึกจำตำแหน่ง"},
  "game.memoryMatch.lowSub": {"en": "{attempts} tries — it's okay, give it another go", "th": "ใช้ {attempts} ครั้ง ไม่เป็นไร ลองเล่นอีก"},
  "game.colorSequence.title": {"en": "Tap in Sequence", "th": "กดปุ่มตามลำดับ"},
  "game.colorSequence.levelLabel": {"en": "Level", "th": "ด่าน"},
  "game.colorSequence.sequenceLabel": {"en": "Sequence", "th": "ลำดับ"},
  "game.colorSequence.colorCount": {"en": "{n} colors", "th": "{n} สี"},
  "game.colorSequence.phaseReady": {"en": "Get ready...", "th": "เตรียมพร้อม..."},
  "game.colorSequence.phaseShowing": {"en": "Watch the sequence!", "th": "จำลำดับให้ดี!"},
  "game.colorSequence.phaseInputting": {"en": "Tap in order!", "th": "กดตามลำดับเลย!"},
  "game.colorSequence.phaseCorrect": {"en": "Correct! Next level", "th": "ถูกต้อง! ไปด่านถัดไป"},
  "game.colorSequence.phaseWrong": {"en": "Wrong! Game over", "th": "ผิด! เกมจบ"},
  "game.colorSequence.resultTitle": {"en": "Tap Sequence Result", "th": "ผลเกมกดปุ่มตามลำดับ"},
  "game.colorSequence.goodMessage": {"en": "Outstanding memory! 🎉", "th": "ความจำเป็นเลิศ! 🎉"},
  "game.colorSequence.okMessage": {"en": "Well done! 👍", "th": "เก่งมาก! 👍"},
  "game.colorSequence.fairMessage": {"en": "Good, try again 💪", "th": "ดีแล้ว ลองอีกครั้ง 💪"},
  "game.colorSequence.lowMessage": {"en": "Keep practicing 🙂", "th": "ค่อย ๆ ฝึกนะ 🙂"},
  "game.colorSequence.goodSub": {"en": "Passed {levels} levels — brilliant sequence memory!", "th": "ผ่าน {levels} ด่าน — จำลำดับได้ยอดเยี่ยม!"},
  "game.colorSequence.okSub": {"en": "Passed {levels} levels — practice more to go even further", "th": "ผ่าน {levels} ด่าน ลองฝึกเพิ่มจะไปได้ไกลกว่านี้"},
  "game.colorSequence.fairSub": {"en": "Passed {levels} levels — keep practicing to improve", "th": "ผ่าน {levels} ด่าน ค่อย ๆ ฝึกจะดีขึ้น"},
  "game.sequence.title": {"en": "Put in Order", "th": "เรียงลำดับ"},
  "game.sequence.tapInOrder": {"en": "Tap in the correct order", "th": "แตะตามลำดับที่ถูกต้อง"},
  "game.sequence.undo": {"en": "Undo", "th": "ย้อนกลับ"},
  "game.sequence.submit": {"en": "Submit", "th": "ส่งคำตอบ"},
  "game.sequence.tapNMore": {"en": "Tap {n} more", "th": "แตะ {n} รายการ"},
  "game.sequence.correct": {"en": "Correct! ✓", "th": "ถูกต้อง! ✓"},
  "game.sequence.wrongOrder": {"en": "Not the right order — see the answer above", "th": "ลำดับยังไม่ถูก ดูเฉลยด้านบน"},
  "game.sequence.nextItem": {"en": "Next", "th": "ข้อถัดไป"},
  "game.sequence.viewScore": {"en": "View Score", "th": "ดูผลคะแนน"},
  "game.sequence.goodSub": {"en": "Excellent sequencing skills", "th": "ทักษะการเรียงลำดับดีเยี่ยม"},
  "assess.appBarTitle": {"en": "Brain Assessment", "th": "แบบประเมินสมอง"},
  "assess.exitTitle": {"en": "Exit the assessment?", "th": "ออกจากแบบประเมิน?"},
  "assess.exitMessage": {"en": "Your progress will not be saved", "th": "ผลที่ทำไปจะไม่ถูกบันทึก"},
  "assess.resultTitle": {"en": "Assessment Result", "th": "ผลการประเมิน"},
  "assess.outOf": {"en": "out of {max}", "th": "จาก {max}"},
  "assess.breakdownDateTime": {"en": "Day/Time", "th": "วัน/เวลา"},
  "assess.breakdownCountdown": {"en": "Countdown", "th": "นับถอยหลัง"},
  "assess.breakdownRecall": {"en": "Word Recall", "th": "จำคำ"},
  "assess.adviceTitle": {"en": "Advice", "th": "ข้อแนะนำ"},
  "assess.adviceBody": {"en": "This is only a preliminary screening, not a diagnosis. If you are concerned, we recommend consulting a doctor for further advice.", "th": "นี่เป็นเพียงการคัดกรองเบื้องต้น ไม่ใช่การวินิจฉัย หากกังวล แนะนำให้ปรึกษาแพทย์เพื่อรับคำแนะนำเพิ่มเติม"},
  "assess.savedResult": {"en": "Result saved", "th": "บันทึกผลแล้ว"},
  "assess.retakeButton": {"en": "Take the assessment again", "th": "ทำแบบประเมินอีกครั้ง"},
  "assess.backHomeButton": {"en": "Back to home", "th": "กลับหน้าหลัก"},
  "assess.tierGoodTitle": {"en": "Excellent! Strong brain", "th": "ดีมาก! สมองแข็งแรง"},
  "assess.tierGoodDesc": {"en": "Your result is in the good range. Keep doing brain-training activities regularly.", "th": "ผลการประเมินอยู่ในเกณฑ์ดี ควรทำกิจกรรมฝึกสมองอย่างสม่ำเสมอ"},
  "assess.tierMediumTitle": {"en": "Moderate, keep practicing", "th": "ปานกลาง ควรฝึกเพิ่ม"},
  "assess.tierMediumDesc": {"en": "Your result is in the moderate range. We recommend training your brain every day.", "th": "ผลการประเมินอยู่ในระดับปานกลาง แนะนำให้ฝึกสมองเป็นประจำทุกวัน"},
  "assess.tierLowTitle": {"en": "You should see a specialist", "th": "ควรพบแพทย์ผู้เชี่ยวชาญ"},
  "assess.tierLowDesc": {"en": "Your result is in a range that could benefit from further care.", "th": "ผลการประเมินอยู่ในระดับที่ควรได้รับการดูแลเพิ่มเติม"},
  "assess.question1of2": {"en": "Question 1/2", "th": "คำถามที่ 1/2"},
  "assess.question2of2": {"en": "Question 2/2", "th": "คำถามที่ 2/2"},
  "assess.whatDayTitle": {"en": "What day is it today?", "th": "วันนี้เป็นวันอะไร?"},
  "assess.whatDaySubtitle": {"en": "Choose the day you think is correct", "th": "เลือกวันที่คุณคิดว่าถูกต้อง"},
  "assess.whatTimeTitle": {"en": "What time of day is it now?", "th": "ตอนนี้เป็นช่วงเวลาใด?"},
  "assess.whatTimeSubtitle": {"en": "Choose the correct time of day", "th": "เลือกช่วงเวลาที่ถูกต้อง"},
  "assess.dayMon": {"en": "Monday", "th": "วันจันทร์"},
  "assess.dayTue": {"en": "Tuesday", "th": "วันอังคาร"},
  "assess.dayWed": {"en": "Wednesday", "th": "วันพุธ"},
  "assess.dayThu": {"en": "Thursday", "th": "วันพฤหัสบดี"},
  "assess.dayFri": {"en": "Friday", "th": "วันศุกร์"},
  "assess.daySat": {"en": "Saturday", "th": "วันเสาร์"},
  "assess.daySun": {"en": "Sunday", "th": "วันอาทิตย์"},
  "assess.periodMorning": {"en": "Morning", "th": "เช้า"},
  "assess.periodNoon": {"en": "Noon", "th": "เที่ยง"},
  "assess.periodEvening": {"en": "Evening", "th": "เย็น"},
  "assess.periodNight": {"en": "Night", "th": "กลางคืน"},
  "assess.memorizeReadyTitle": {"en": "Memory Test", "th": "ทดสอบความจำ"},
  "assess.memorizeReadyBody": {"en": "3 words will be shown. You have {seconds} seconds to memorize them.\nAfter that, we will ask you again.", "th": "จะแสดงคำ 3 คำ ให้เวลาจำ {seconds} วินาที\nหลังจากนั้นจะถามอีกครั้ง"},
  "assess.readyStartButton": {"en": "I'm ready, let's start!", "th": "พร้อมแล้ว เริ่มเลย!"},
  "assess.secondsLabel": {"en": "seconds", "th": "วินาที"},
  "assess.memorizeTheseWords": {"en": "Memorize these words", "th": "จำคำเหล่านี้ให้ได้"},
  "assess.almostOutOfTime": {"en": "Almost out of time!", "th": "ใกล้หมดเวลาแล้ว!"},
  "assess.timeUpTitle": {"en": "Time's up!", "th": "หมดเวลา!"},
  "assess.timeUpBody": {"en": "We'll ask about these words again later.\nLet's move on to the next question.", "th": "เราจะถามคำเหล่านี้อีกครั้งทีหลัง\nไปทำข้อต่อไปกันเลย"},
  "assess.nextQuestion": {"en": "Next question", "th": "ไปข้อถัดไป"},
  "assess.countdownInstruction": {"en": "Count down from 20, subtracting 3 each time", "th": "นับถอยหลังจาก 20 ลบครั้งละ 3"},
  "assess.answerNumber": {"en": "Answer {n}", "th": "คำตอบที่ {n}"},
  "assess.startingNumberQuestion": {"en": "What number do you start from?", "th": "เริ่มจากตัวเลขอะไร?"},
  "assess.minusThreeQuestion": {"en": "What is {value} minus 3?", "th": "{value} ลบ 3 ได้เท่าไหร่?"},
  "assess.allAnsweredTitle": {"en": "All answered!", "th": "ตอบครบแล้ว!"},
  "assess.correctOutOfFive": {"en": "{score} correct out of 5", "th": "ถูก {score} จาก 5 ข้อ"},
  "assess.yourAnswer": {"en": "You answered: {answer}", "th": "คุณตอบ: {answer}"},
  "assess.correctAnswer": {"en": "Answer: {answer}", "th": "เฉลย: {answer}"},
  "assess.recallTitle": {"en": "Can you recall the words?", "th": "จำคำได้ไหม?"},
  "assess.recallSubtitle": {"en": "Select the words you saw earlier", "th": "เลือกคำที่คุณเห็นก่อนหน้านี้"},
  "assess.pickCount": {"en": "Pick {count} words", "th": "เลือกได้ {count} คำ"},
  "assess.pickLimitReached": {"en": "You can pick only {count} words. Remove one before selecting a new one.", "th": "เลือกได้ {count} คำเท่านั้น กดเอาออกก่อนเลือกใหม่"},
  "assess.selectRememberedWords": {"en": "Select the words you remember", "th": "เลือกคำที่จำได้"},
  "assess.confirmAnswer": {"en": "Confirm answer ({selected}/{total})", "th": "ยืนยันคำตอบ ({selected}/{total})"},
  "profile.ageRange": {"en": "Age Range", "th": "ช่วงอายุ"},
  "profile.gender": {"en": "Gender", "th": "เพศ"},
  "family.callTitle": {"en": "Call Family", "th": "โทรหาครอบครัว"},
  "family.callFailed": {"en": "Call failed", "th": "โทรออกไม่สำเร็จ"},
  "family.callNotSupported": {"en": "This device can't make calls", "th": "อุปกรณ์นี้โทรออกไม่ได้"},
  "family.addMember": {"en": "Add Member", "th": "เพิ่มสมาชิก"},
  "family.editMember": {"en": "Edit Member", "th": "แก้ไขสมาชิก"},
  "family.deleteTitle": {"en": "Delete contact?", "th": "ลบรายชื่อ?"},
  "family.deleteConfirm": {"en": "Remove \"{name}\" from your family list?", "th": "ต้องการลบ \"{name}\" ออกจากรายชื่อครอบครัวหรือไม่"},
  "family.call": {"en": "Call", "th": "โทร"},
  "family.emptyTitle": {"en": "No family members yet", "th": "ยังไม่มีรายชื่อครอบครัว"},
  "family.emptyBody": {"en": "Add your loved ones' photos and numbers\nfor easy one-tap calling", "th": "เพิ่มรูปและเบอร์ของลูกหลาน\nไว้กดโทรได้ง่าย ๆ"},
  "family.addFirstMember": {"en": "Add your first member", "th": "เพิ่มสมาชิกคนแรก"},
  "family.photoPickFailed": {"en": "Couldn't select photo", "th": "เลือกรูปไม่สำเร็จ"},
  "family.namePhoneRequired": {"en": "Please enter a name and phone number", "th": "กรุณากรอกชื่อและเบอร์โทร"},
  "family.addPhoto": {"en": "Add photo", "th": "เพิ่มรูป"},
  "family.changePhoto": {"en": "Change photo", "th": "เปลี่ยนรูป"},
  "family.nameLabel": {"en": "Name", "th": "ชื่อ"},
  "family.nameHint": {"en": "e.g. Daughter, Grandson", "th": "เช่น ลูกสาว, หลานชาย"},
  "family.phoneLabel": {"en": "Phone number", "th": "เบอร์โทรศัพท์"},
  "family.phoneHint": {"en": "e.g. 0812345678", "th": "เช่น 0812345678"},
  "family.lineIdLabel": {"en": "LINE User ID (optional)", "th": "LINE User ID (ไม่บังคับ)"},
  "family.lineIdDesc": {"en": "For sending drowsiness alerts to this person via LINE", "th": "สำหรับส่งแจ้งเตือนอาการง่วงไปหาคนนี้ผ่าน LINE"},
  "family.lineIdHint": {"en": "Uxxxxxxxx… (from adding the LINE OA)", "th": "Uxxxxxxxx… (ได้จากการแอด LINE OA)"},
  "family.save": {"en": "Save", "th": "บันทึก"},
  "family.lineTitle": {"en": "Notify Family via LINE", "th": "แจ้งครอบครัวผ่าน LINE"},
  "family.lineOpenFailed": {"en": "Couldn't open LINE", "th": "เปิด LINE ไม่สำเร็จ"},
  "family.testBroadcastMessage": {"en": "Test alert from Demenish AI — if you see this message, you're all set", "th": "ทดสอบแจ้งเตือนจาก Demenish AI — ถ้าเห็นข้อความนี้แปลว่าพร้อมแล้ว"},
  "family.testSent": {"en": "Test message sent — check LINE on the phones that added the OA", "th": "ส่งข้อความทดสอบแล้ว — เช็ก LINE ของคนที่แอด OA"},
  "family.testNotConfigured": {"en": "Can't send yet (this app isn't configured for LINE — build it with --dart-define)", "th": "ยังส่งไม่ได้ (แอปนี้ยังไม่ได้ตั้งค่า LINE — ต้อง build ด้วย --dart-define)"},
  "family.lineIntro": {"en": "Have your loved ones scan this QR to get alerts\nwhen the elder shows signs of drowsiness/fatigue", "th": "ให้ลูกหลานสแกน QR นี้เพื่อรับแจ้งเตือน\nเมื่อผู้สูงอายุมีอาการง่วง/เหนื่อยล้า"},
  "family.openLineToAdd": {"en": "Open LINE to add", "th": "เปิด LINE เพื่อแอด"},
  "family.step1": {"en": "Your loved one opens the LINE app on their own phone", "th": "ลูกหลานเปิดแอป LINE บนมือถือตัวเอง"},
  "family.step2": {"en": "Scan this QR (or tap Open LINE) and add \"Demenish-AI\" as a friend", "th": "สแกน QR นี้ (หรือกดปุ่มเปิด LINE) แล้วแอด \"Demenish-AI\" เป็นเพื่อน"},
  "family.step3": {"en": "Turn on the \"Drowsiness Detection\" feature in Settings", "th": "เปิดฟีเจอร์ \"ตรวจจับอาการง่วง\" ในหน้าตั้งค่า"},
  "family.step4": {"en": "When the app detects drowsiness, everyone who added it gets a LINE alert", "th": "เมื่อแอปพบอาการง่วง ทุกคนที่แอดจะได้รับแจ้งเตือนใน LINE"},
  "family.testSend": {"en": "Send test alert", "th": "ทดสอบส่งแจ้งเตือน"},
  "family.notConfiguredNotice": {"en": "This app isn't configured to connect to LINE — build it with --dart-define (see docs/backend) to send real alerts", "th": "แอปนี้ยังไม่ได้ตั้งค่าเชื่อม LINE — ต้อง build ด้วย --dart-define (ดู docs/backend) จึงจะส่งแจ้งเตือนจริงได้"},
  "scam.title": {"en": "Scam Message Check", "th": "ตรวจข้อความหลอกลวง"},
  "scam.intro": {"en": "Suspect an SMS or message is a scam?\nPaste it here to check.", "th": "สงสัยว่า SMS หรือข้อความไหนหลอกลวง?\nวางข้อความมาตรวจได้เลย"},
  "scam.inputHint": {"en": "Paste or type the message here…", "th": "วางหรือพิมพ์ข้อความที่นี่…"},
  "scam.paste": {"en": "Paste", "th": "วางข้อความ"},
  "scam.check": {"en": "Check", "th": "ตรวจสอบ"},
  "scam.clear": {"en": "Clear text", "th": "ล้างข้อความ"},
  "scam.clipboardEmpty": {"en": "No text in the clipboard", "th": "ไม่มีข้อความในคลิปบอร์ด"},
  "scam.riskLabel": {"en": "Risk", "th": "ความเสี่ยง"},
  "scam.detected": {"en": "What we found", "th": "สิ่งที่ตรวจพบ"},
  "flash.todayCard": {"en": "Today's Card", "th": "การ์ดวันนี้"},
  "flash.reveal": {"en": "Show answer", "th": "เฉลย"},
  "flash.answerInMind": {"en": "Try answering in your head", "th": "ลองตอบในใจดูนะ"},
  "flash.close": {"en": "Close", "th": "ปิด"},
  "appt.title": {"en": "Doctor Appointments", "th": "นัดหมายแพทย์"},
  "appt.add": {"en": "Add", "th": "เพิ่มนัด"},
  "appt.deleteTitle": {"en": "Delete appointment?", "th": "ลบนัดหมาย?"},
  "appt.deleteConfirm": {"en": "Delete \"{title}\"?", "th": "ต้องการลบ \"{title}\" หรือไม่"},
  "appt.dateTimeLine": {"en": "{date}  {time}", "th": "{date}  {time} น."},
  "appt.emptyTitle": {"en": "No appointments yet", "th": "ยังไม่มีนัดหมาย"},
  "appt.emptyBody": {"en": "Add a doctor's appointment\nand the app will remind you before it's time", "th": "เพิ่มนัดหมายแพทย์\nแล้วแอปจะเตือนก่อนถึงเวลา"},
  "appt.addFirst": {"en": "Add your first appointment", "th": "เพิ่มนัดหมายแรก"},
  "appt.titleRequired": {"en": "Please enter an appointment title", "th": "กรุณากรอกหัวข้อนัดหมาย"},
  "appt.editHeader": {"en": "Edit Appointment", "th": "แก้ไขนัดหมาย"},
  "appt.addHeader": {"en": "Add Appointment", "th": "เพิ่มนัดหมาย"},
  "appt.titleField": {"en": "Appointment title", "th": "หัวข้อนัดหมาย"},
  "appt.titleHint": {"en": "e.g. Diabetes check-up, See cardiologist", "th": "เช่น ตรวจเบาหวาน, พบหมอหัวใจ"},
  "appt.dateLabel": {"en": "Date", "th": "วันที่"},
  "appt.timeLabel": {"en": "Time", "th": "เวลา"},
  "appt.timeValue": {"en": "{time}", "th": "{time} น."},
  "appt.locationField": {"en": "Place / Doctor", "th": "สถานที่ / แพทย์"},
  "appt.locationHint": {"en": "e.g. Siriraj Hospital, Internal Medicine", "th": "เช่น รพ.ศิริราช แผนกอายุรกรรม"},
  "appt.reminderField": {"en": "Remind me in advance", "th": "เตือนล่วงหน้า"},
  "appt.noteField": {"en": "Additional notes", "th": "บันทึกเพิ่มเติม"},
  "appt.noteHint": {"en": "e.g. Fast (no food or water) before the test", "th": "เช่น งดน้ำงดอาหารก่อนตรวจ"},
  "appt.save": {"en": "Save appointment", "th": "บันทึกนัดหมาย"},
  "screen.title": {"en": "Screen Time", "th": "จำกัดเวลาหน้าจอ"},
  "screen.overLimitTitle": {"en": "Time's up!", "th": "ใช้เกินเวลาแล้ว!"},
  "screen.overLimitMessage": {"en": "It's time to rest your eyes.\nTry taking a walk or having a glass of water.", "th": "ถึงเวลาพักสายตาแล้วนะคะ\nลองออกไปเดินเล่น หรือดื่มน้ำสักแก้ว"},
  "screen.stopTimer": {"en": "Stop timer", "th": "หยุดจับเวลา"},
  "screen.acknowledgeContinue": {"en": "Got it, keep using", "th": "รับทราบ ใช้ต่อ"},
  "screen.tracking": {"en": "Timing...", "th": "กำลังจับเวลา..."},
  "screen.used": {"en": "Used", "th": "ใช้ไปแล้ว"},
  "screen.dailyLimitLabel": {"en": "Daily limit {limit}", "th": "จำกัดวันละ {limit}"},
  "screen.overLimitWarning": {"en": "You've exceeded your limit. You should rest your eyes.", "th": "ใช้เกินเวลาที่กำหนดแล้ว ควรพักสายตา"},
  "screen.startTimer": {"en": "Start timer", "th": "เริ่มจับเวลา"},
  "screen.resetToday": {"en": "Reset today's time", "th": "รีเซ็ตเวลาวันนี้"},
  "screen.limitSaved": {"en": "Saved: limit {h} h {m} min/day", "th": "บันทึกแล้ว: จำกัด {h} ชั่วโมง {m} นาที/วัน"},
  "screen.setLimit": {"en": "Set limit", "th": "ตั้งเวลาจำกัด"},
  "screen.hours": {"en": "hours", "th": "ชั่วโมง"},
  "screen.minutes": {"en": "minutes", "th": "นาที"},
  "screen.saveLimit": {"en": "Save limit", "th": "บันทึกเวลา"},
  "screen.weekSummary": {"en": "This week's summary", "th": "สรุปสัปดาห์นี้"},
  "screen.noWeekData": {"en": "No data for this week yet.\nTap \"Start timer\" to begin recording.", "th": "ยังไม่มีข้อมูลสัปดาห์นี้\nกด \"เริ่มจับเวลา\" เพื่อเริ่มบันทึก"},
  "screen.dayMon": {"en": "Mon", "th": "จ"},
  "screen.dayTue": {"en": "Tue", "th": "อ"},
  "screen.dayWed": {"en": "Wed", "th": "พ"},
  "screen.dayThu": {"en": "Thu", "th": "พฤ"},
  "screen.dayFri": {"en": "Fri", "th": "ศ"},
  "screen.daySat": {"en": "Sat", "th": "ส"},
  "screen.daySun": {"en": "Sun", "th": "อา"},
  "history.title": {"en": "Score History", "th": "ประวัติคะแนน"},
  "history.pastAssessments": {"en": "Past assessments", "th": "ผลการประเมินที่ผ่านมา"},
  "history.noAssessments": {"en": "No assessment results yet.\nTap \"Assess\" to begin.", "th": "ยังไม่มีผลการประเมิน\nกด \"ประเมิน\" เพื่อเริ่ม"},
  "history.recentGameScores": {"en": "Recent game scores", "th": "คะแนนเกมล่าสุด"},
  "history.soundMatch": {"en": "Sound Match", "th": "จับคู่เสียง"},
  "history.sequence": {"en": "Sequence", "th": "เรียงลำดับ"},
  "history.noGameScores": {"en": "No game scores yet.\nTry playing a brain-training game!", "th": "ยังไม่มีคะแนนเกม\nลองเล่นเกมฝึกสมองดูสิ"},
  "history.noData": {"en": "No data yet", "th": "ยังไม่มีข้อมูล"},
  "history.avgLast5": {"en": "Average of last 5", "th": "เฉลี่ย 5 ครั้งล่าสุด"},
  "history.trend": {"en": "Trend", "th": "แนวโน้ม"},
  "history.doAssessmentForTrend": {"en": "Take an assessment to see your trend", "th": "ทำแบบประเมินเพื่อดูแนวโน้ม"},
  "history.thisWeekCount": {"en": "You took {n} assessment(s) this week", "th": "สัปดาห์นี้คุณทำแบบประเมิน {n} ครั้ง"},
  "history.needThreeForTrend": {"en": "Take at least 3 assessments to see your trend", "th": "ทำแบบประเมินอย่างน้อย 3 ครั้งเพื่อดูแนวโน้ม"},
  "history.trendNotEnough": {"en": "Not enough data yet", "th": "ยังไม่มีข้อมูลเพียงพอ"},
  "history.trendImproved": {"en": "Improving! Strong brain", "th": "ดีขึ้น! สมองแข็งแรง"},
  "history.trendPracticeMore": {"en": "Practice more", "th": "ควรฝึกเพิ่ม"},
  "history.trendSteady": {"en": "Steady, doing well", "th": "คงที่ ทำได้ดีอยู่"},
  "history.trendGoodStart": {"en": "Great start, strong brain", "th": "เริ่มต้นดี สมองแข็งแรง"},
  "history.trendDeveloping": {"en": "Developing, keep practicing", "th": "กำลังพัฒนา ฝึกต่อไป"},
  "history.trendShouldPractice": {"en": "You should train your brain more", "th": "ควรฝึกสมองเพิ่มเติม"},
  "common.exitTitle": {"en": "Leave this page?", "th": "ออกจากหน้านี้?"},
  "common.exitMessage": {"en": "Your progress will be lost", "th": "ข้อมูลที่ทำไปจะหายหมด"},
  "common.continue": {"en": "Continue", "th": "ทำต่อ"},
  "common.exit": {"en": "Exit", "th": "ออก"},
  "splash.tagline": {"en": "A Brain Tracker App", "th": "แอปติดตามสุขภาพสมอง"},
  "tips.todayHeader": {"en": "Today's tip", "th": "คำแนะนำวันนี้"},
  "tips.default1": {"en": "Read a book or magazine for 15 minutes a day to stimulate your brain", "th": "อ่านหนังสือหรือนิตยสารวันละ 15 นาที ช่วยกระตุ้นสมอง"},
  "tips.default2": {"en": "Try learning something new every day, like one new word", "th": "ลองเรียนรู้สิ่งใหม่ ๆ ทุกวัน เช่น คำศัพท์ใหม่ 1 คำ"},
  "tips.default3": {"en": "Do light exercise like walking to keep your brain healthy", "th": "ออกกำลังกายเบา ๆ เช่น เดินเล่น ช่วยให้สมองแข็งแรง"},
  "tips.default4": {"en": "Get enough sleep, 7-8 hours, so your brain can rest", "th": "นอนหลับให้เพียงพอ 7-8 ชั่วโมง สมองจะได้พักผ่อน"},
  "tips.default5": {"en": "Eat omega-3 rich foods like fish to nourish your brain", "th": "ทานอาหารที่มีโอเมก้า 3 เช่น ปลา ช่วยบำรุงสมอง"},
  "tips.playSoundGame": {"en": "Try playing the Sound Match game once a day to train your memory", "th": "ลองเล่นเกมจับคู่เสียงวันละ 1 ครั้ง เพื่อฝึกความจำ"},
  "tips.improved": {"en": "Excellent! Your brain is getting stronger 🌟 Keep it up", "th": "เยี่ยมมาก! สมองแข็งแรงขึ้น 🌟 ทำต่อไปนะ"},
  "reminder.atTime": {"en": "At the time", "th": "ตอนถึงเวลา"},
  "reminder.min30": {"en": "30 min before", "th": "ก่อน 30 นาที"},
  "reminder.hour1": {"en": "1 hour before", "th": "ก่อน 1 ชั่วโมง"},
  "reminder.hour3": {"en": "3 hours before", "th": "ก่อน 3 ชั่วโมง"},
  "reminder.day1": {"en": "1 day before", "th": "ก่อน 1 วัน"},
  "scamrisk.low.label": {"en": "Looks safe", "th": "ดูปลอดภัย"},
  "scamrisk.low.advice": {"en": "No clear scam signals found, but if unsure, ask a family member.", "th": "ไม่พบสัญญาณหลอกลวงชัดเจน แต่ถ้าไม่แน่ใจ ลองถามลูกหลานดูนะ"},
  "scamrisk.medium.label": {"en": "Suspicious", "th": "น่าสงสัย"},
  "scamrisk.medium.advice": {"en": "There are signs to be careful of. Verify before acting on it.", "th": "มีสัญญาณที่ต้องระวัง ตรวจสอบให้แน่ใจก่อนทำตาม"},
  "scamrisk.high.label": {"en": "High risk", "th": "เสี่ยงสูง"},
  "scamrisk.high.advice": {"en": "Do not tap links, do not transfer money, do not share personal info. Call a family member first.", "th": "อย่ากดลิงก์ อย่าโอนเงิน อย่าให้ข้อมูลส่วนตัว โทรถามลูกหลานก่อน"},
  "scam.reason.highKeyword": {"en": "Contains words often used in scams: {items}", "th": "มีคำที่มักใช้หลอกลวง: {items}"},
  "scam.reason.medKeyword": {"en": "Contains persuasive/urgent words: {items}", "th": "มีคำชวนเชื่อ/เร่งรีบ: {items}"},
  "scam.reason.hasUrl": {"en": "Contains a link — always be careful before tapping", "th": "มีลิงก์ให้กด — ระวังก่อนกดทุกครั้ง"},
  "scam.reason.ipUrl": {"en": "The link is a numeric IP instead of a site name (common in fake sites)", "th": "ลิงก์เป็นตัวเลข IP แทนชื่อเว็บ (พบมากในเว็บปลอม)"},
  "scam.reason.shortener": {"en": "Uses a link shortener that hides the destination: {items}", "th": "ใช้ลิงก์ย่อที่ซ่อนปลายทาง: {items}"},
  "scam.reason.suspiciousTld": {"en": "Unusual domain ({items}) — not an official site", "th": "โดเมนแปลก ({items}) ไม่ใช่เว็บทางการ"},
  "notif.appointmentTitle": {"en": "Appointment: {title}", "th": "นัดหมาย: {title}"},
  "notif.appointmentBody": {"en": "Today at {time}{place}", "th": "วันนี้เวลา {time} น.{place}"},
  "notif.appointmentPlace": {"en": " at {place}", "th": " ที่ {place}"},
  "notif.drowsyTitle": {"en": "Take a short rest", "th": "พักสักครู่นะ"},
  "notif.drowsyBody": {"en": "You seem drowsy — rest your eyes or take a short nap", "th": "ดูเหมือนกำลังง่วง ลองพักสายตาหรืองีบสักครู่"},
  "notif.drowsyLine": {"en": "{who} seems drowsy/tired — please give them a call to check in", "th": "{who} ดูเหมือนกำลังง่วง/เหนื่อยล้า ลองโทรถามอาการหน่อยนะ"},
  "notif.someoneAtHome": {"en": "Someone at home", "th": "คนที่บ้าน"},
  "flash.q.who": {"en": "Who is this?", "th": "คนนี้คือใคร?"},
  "flash.prompt1": {"en": "What day is it today?", "th": "วันนี้เป็นวันอะไร?"},
  "flash.prompt2": {"en": "About what time is it now?", "th": "ตอนนี้ประมาณกี่โมงแล้ว?"},
  "flash.prompt3": {"en": "What did you have this morning?", "th": "เมื่อเช้ารับประทานอะไร?"},
  "flash.prompt4": {"en": "What month is it?", "th": "เดือนนี้เดือนอะไร?"},
  "flash.prompt5": {"en": "What do you plan to do tomorrow?", "th": "พรุ่งนี้ตั้งใจจะทำอะไร?"},
  "flash.prompt6": {"en": "Who did you talk to yesterday?", "th": "เมื่อวานได้คุยกับใครบ้าง?"},
  "flash.prompt7": {"en": "Where are you right now?", "th": "ตอนนี้อยู่ที่ไหน?"},
};
